export const ROUTES = {
    HOME: '/',
    LANGUAGE_SELECTION: '/language-selection',
    LANDING: '/landing',
    LOGIN: '/login',
    SIGNUP: '/signup',
    VERIFY_OTP: '/verify-otp',
    SUCCESS: '/success',
    REGISTRATION_FORM: '/registration-form',
    APPLICATION_STATUS: '/application-status',
    DASHBOARD: '/dashboard',
    REPORTS: '/seller/reports',
    MASTERS: '/seller/masters',
    PURCHASE: '/seller/purchase',
    PURCHASE_ORDER: '/seller/purchase/order',
    PURCHASE_ORDER_ADD: '/seller/purchase/order/add',
    PURCHASE_ORDER_EDIT: '/seller/purchase/order/edit/:id',
    PURCHASE_ORDER_VIEW: '/seller/purchase/order/view/:id',
    PURCHASE_ORDER_PRINT: '/seller/purchase/order/print',
    PURCHASE_INVOICE: '/seller/purchase/invoice',
    SALES: '/seller/sales',
    SETTINGS: '/seller/settings',
    SELLER_DASHBOARD: '/seller/dashboard',
    SUPERADMIN_DASHBOARD: '/superadmin/dashboard',
    SUPERADMIN_PENDING_SELLERS: '/superadmin/pending-sellers',
    SUPERADMIN_APPROVED_SELLERS: '/superadmin/approved-sellers',
    SUPERADMIN_REJECTED_SELLERS: '/superadmin/rejected-sellers',
};
