export const ROUTES = {
    HOME: '/',
    LANGUAGE_SELECTION: '/language-selection',
    LANDING: '/landing',
    LOGIN: '/login',
    SIGNUP: '/signup',
    VERIFY_OTP: '/verify-otp',
    SUCCESS: '/success',
    REGISTRATION_FORM: '/registration-form',
    APPLICATION_STATUS: '/application-status',
    DASHBOARD: '/dashboard',
    REPORTS: '/dashboard/reports',
    MASTERS: '/dashboard/masters',
    PURCHASE: '/dashboard/purchase',
    SALES: '/dashboard/sales',
    SETTINGS: '/dashboard/settings',
    SELLER_DASHBOARD: '/seller/dashboard',
    SUPERADMIN_DASHBOARD: '/superadmin/dashboard',
    SUPERADMIN_PENDING_SELLERS: '/superadmin/pending-sellers',
    SUPERADMIN_APPROVED_SELLERS: '/superadmin/approved-sellers',
    SUPERADMIN_REJECTED_SELLERS: '/superadmin/rejected-sellers',
};
